// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniversalIdentity.Infra.Data.Context;

namespace UniversalIdentity.Infra.Data.Migrations
{
    [DbContext(typeof(UniversalIdentityContext))]
    [Migration("20211119004642_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UniversalIdentity.Domain.Entities.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataUltimoAcesso")
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_ULTIMO_ACESSO");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("EMAIL");

                    b.Property<int>("PessoaId")
                        .HasColumnType("int")
                        .HasColumnName("PESSOA_ID");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("SENHA");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId");

                    b.ToTable("T_LOGIN");
                });

            modelBuilder.Entity("UniversalIdentity.Domain.Entities.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<DateTime?>("DataCadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_CADASTRO");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_NASCIMENTO");

                    b.Property<DateTime?>("DocumentoDataEmissao")
                        .IsRequired()
                        .HasColumnType("datetime2")
                        .HasColumnName("DOCUMENTO_DT_EMISSAO");

                    b.Property<string>("DocumentoNumero")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("DOCUMENTO_NUMERO");

                    b.Property<int>("DocumentoTipo")
                        .HasColumnType("int")
                        .HasColumnName("DOCUMENTO_TIPO");

                    b.Property<int>("Genero")
                        .HasColumnType("int")
                        .HasColumnName("GENERO");

                    b.Property<string>("ImagemPerfilBase64")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IMAGEM_PERFIL_BASE64");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NOME");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("STATUS");

                    b.Property<double>("TotalAvaliacao")
                        .HasColumnType("float")
                        .HasColumnName("TOTAL_AVALIACAO");

                    b.Property<int>("TotalHorasTrabalhadas")
                        .HasColumnType("int")
                        .HasColumnName("TOTAL_HORAS_TRABALHADAS");

                    b.Property<string>("UniversalId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("UNIVERSAL_ID");

                    b.Property<string>("UniversalIdBase64")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UNIVERSAL_ID_BASE64");

                    b.HasKey("Id");

                    b.ToTable("T_PESSOA");
                });

            modelBuilder.Entity("UniversalIdentity.Domain.Entities.Login", b =>
                {
                    b.HasOne("UniversalIdentity.Domain.Entities.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });
#pragma warning restore 612, 618
        }
    }
}
